WEB/Controllers/SessionController.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using Web.Core.Common;
using Web.Core.Interface;
using Web.Core.ViewModel;

namespace WEB.Controllers
{
    public class SessionController : Controller
    {
        IGlobal _global;
        CommonServices _service;

        public SessionController(IGlobal global)
        {
            _global = global;
            _service = new CommonServices(_global);

        }

        //Get Session
        [HttpGet]
        public ActionResult Index()
        {
            var _SessionDetails = _service.Get<ApiResponseViewModel<SessionMasterDataModel>>(_global.ApiUrl() + "/api/v1/session/getsessiondetails").Item3;
            return View(_SessionDetails.Data);
        }

        //Get Session By Name
        [HttpPost]
        public ActionResult Index(String SessionName)
        {
            var param = string.IsNullOrEmpty(SessionName) ? "" : "?sessionName=" + SessionName;
            var _SessionDetails = _service.Get<ApiResponseViewModel<SessionMasterDataModel>>(_global.ApiUrl() + "/api/v1/session/getsessiondetails" + param).Item3;
            return View(_SessionDetails.Data);
        }

        public ActionResult AddUpdateSession(int? SessionID = null)
        {
            SessionInsertUpdateRequestModel model = new SessionInsertUpdateRequestModel();
            if (SessionID.HasValue)
            {
                var _SessionDetails = _service.Get<object>(_global.ApiUrl() + "/api/v1/session/getsessiondetails?SessionID=" + SessionID);
                var outout  = JsonConvert.DeserializeObject<ApiResponseViewModel<SessionMasterDataModel>>(JsonConvert.SerializeObject(_SessionDetails.Item3))?.Data?.FirstOrDefault();
                if (outout != null)
                {
                    model.SessionID = outout.SessionID;
                    model.SessionName = outout.SessionName;
                    model.SessionDesc = outout.SessionDescription;
                    model.IsActive = outout.IsActive?1:0;
                    model.PrincipalSignaturePath = outout.PrincipalSignature;
                }
            }

            return View(model);
        }

        [HttpPost]
        public ActionResult AddUpdateSession(SessionInsertUpdateRequestModel model)
        {
            if (!ModelState.IsValid)
                return View(model);

            var identity = User.Identity as ClaimsIdentity;
            var userID = identity.Claims.Where(m => m.Type == "UserID").FirstOrDefault().Value ?? "0";
            model.CreatedBy =Convert.ToInt32(userID);

            var jSon = new JavaScriptSerializer().Serialize(model);
            var res = _service.Post<CommonResponseDataModel>(_global.ApiUrl() + "/api/v1/session/insertupdatesession", jSon);

            if (res.Item3 != null && !res.Item3.Successful)
            {
                ViewBag.Error = "Unable to save session!";
            }

            if (res.Item3 != null && res.Item3.ReturnID > 0)
            {
                model.SessionID = res.Item3.ReturnID;

                return RedirectToAction("Index");
            }

            return View(model);
        }

    }
}

WEB/Views/Session/AddUpdateSession.cshtml
@model Web.Core.ViewModel.SessionInsertUpdateRequestModel
@{
    ViewBag.PageTitle = "Session Add/Update";
    string isError = "none";
    string errMsg = "";
    if (ViewBag.Error != null)
    {
        errMsg = ViewBag.Error;
        isError = "block";
    }
}

<div class="container-fluid">
    <div class="user justify-content-center">
        <div class="col-xl-12 col-md-12 mb-4 p-0">
            <div class="card shadow-0 py-2">
                <div class="card-body p-2">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2 pl-2">
                            <div class="text-xl font-weight-600 mb-3 card-Title">Session Details</div>
                            <p style="display:@isError">@errMsg</p>
                            @using (Html.BeginForm("AddUpdateSession", "Session", FormMethod.Post, new { @class = "user justify-content-center", id = "SessionInsert", novalidate = "novalidate" }))
                            {
                                <input type="hidden" name="SessionID" value="@Model.SessionID" id="SessionID" />
                                <input type="hidden" name="IsActive" value="@(Model.SessionID > 0 ? Model.IsActive : 1)" id="IsActive" />
                                <div class="">
                                    <div class="form-group row">
                                        <div class="col-sm-6 mb-3 mb-sm-0">
                                            <label>Session Name<span class="text-danger">*</span></label>
                                            @Html.TextBoxFor(m => m.SessionName, new { @class = "form-control form-control-user", placeholder = "Session Name", data_validation = "required" })
                                        </div>
                                        <div class="col-sm-6">
                                            <label>Session Description</label>
                                            @Html.TextBoxFor(m => m.SessionDesc, new { @class = "form-control form-control-user", placeholder = "Session Description" })
                                        </div>
                                    </div>

                                    <div class="text-right">
                                        <input type="submit" class="btn btn-primary" value="@(Model.SessionID > 0 ? "Update" : "Save")" />
                                    </div>
                                </div>
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="~/Content/js/jquery.1.10.2.min.js"></script>
<script src="~/Content/js/jquery.validate.min.js"></script>
<script src="~/Content/js/myScript.js"></script>

WEB/Views/Session/Index.cshtml
@model IEnumerable<Web.Core.ViewModel.SessionMasterDataModel>
@{
    ViewBag.PageTitle = "Session Master";
}

<!DOCTYPE html>

<div class="container-fluid">
    @* <h1 class="h3 mb-4 text-gray-800">Branch Users</h1>*@

    @using (Html.BeginForm("Index", "Session", FormMethod.Post, new { id = "frmSearch" }))
    {
        <div class="form-group row">
            <div class="col-sm-4 mb-3 mb-sm-0">
                @* <h1 class="h3 mb-4 text-gray-800">Branch List</h1>*@
            </div>
            <div class="col-sm-4  mb-3 mb-sm-0">
            </div>
            <div class="col-sm-4">
                <div class="input-group">
                    @Html.TextBox("SessionNAme", "", new { @class = "form-control border-0 small", @placeholder = "Search", @onchange = "SearchBySession()" })
                    <div class="input-group-append">
                        <button class="btn btn-primary" type="button">
                            <i class="fas fa-search fa-sm"></i>
                        </button>
                    </div>
                </div>
            </div>
        </div>
    }
    <div class="justify-content-center row mb-3">
        <div class="col-xl-12 col-md-12 mb-1">
            <div class="card shadow mb-4">
                <div class="card-body">
                    <table class="table table-active table-bordered dt-responsive nowrap" style="width:100%">
                        <thead>
                            <tr class="bg-light">

                                <th>Session Name</th>
                                <th>Session Description</th>

                                <th class="with-50">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>@item.SessionName</td>
                                    <td>@item.SessionDescription</td>
                                    <td><a href="Session/AddUpdateSession?SessionID=@item.SessionID" class="text-info p-1"><i class="fas fa-user-edit"></i></a></td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

@section script{

    <script>

        function SearchBySession() {
            $("#frmSearch").submit();
        }
    </script>
}