WEB/Controllers/BranchController.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using Web.Core.Common;
using Web.Core.Interface;
using Web.Core.ViewModel;

namespace WEB.Controllers
{
    public class BranchController : Controller
    {
        IGlobal _global;
        CommonServices _service;

        public BranchController(IGlobal global)
        {
            _global = global;
            _service = new CommonServices(_global);

        }

        // GET: Branch
        [HttpGet]
        public ActionResult Index()
        {
            var _BranchDetails = _service.Get<ApiResponseViewModel<BranchDetailsDataModel>>(_global.ApiUrl() + "/api/v1/branch/getbranchdetails").Item3;

            //var branch = JsonConvert.DeserializeObject<ApiResponseViewModel<BranchDetailsDataModel>>(JsonConvert.SerializeObject(_BranchDetails.Item3)).Data;
            // var edit = branch.Branch;
            //  branch.BranchOwners = branch.BranchOwners ?? new List<BranchOwnerDataModel>();
            return View(_BranchDetails.Data);
        }

        [HttpPost]
        public ActionResult Index(String BranchName)
        {
            var param = string.IsNullOrEmpty(BranchName) ? "" : "?branchName=" + BranchName;
            var _BranchDetails = _service.Get<ApiResponseViewModel<BranchDetailsDataModel>>(_global.ApiUrl() + "/api/v1/branch/getbranchdetails" + param).Item3;

            //var branch = JsonConvert.DeserializeObject<ApiResponseViewModel<BranchDetailsDataModel>>(JsonConvert.SerializeObject(_BranchDetails.Item3)).Data;
            // var edit = branch.Branch;
            //  branch.BranchOwners = branch.BranchOwners ?? new List<BranchOwnerDataModel>();
            return View(_BranchDetails.Data);
        }
        public ActionResult AddUpdateBranch(int? BranchID = null)
        {
            // BranchID = 26;
            BranchDetailsInsertUpdateRequestModel model = new BranchDetailsInsertUpdateRequestModel();
            model.Owners = new List<BranchCreateOwnerRequestModel>();
            if (BranchID.HasValue)
            {

                var _BranchDetails = _service.Get<object>(_global.ApiUrl() + "/api/v1/branch/getbranchdetails?BranchID=" + BranchID);
                var branch = JsonConvert.DeserializeObject<ApiResponseViewModel<BranchDetailsDataModel>>(JsonConvert.SerializeObject(_BranchDetails.Item3)).Data.FirstOrDefault();
                var edit = branch.Branch;
                branch.BranchOwners = branch.BranchOwners ?? new List<BranchOwnerDataModel>();
                model = new BranchDetailsInsertUpdateRequestModel()
                {
                    GP_Municipality = edit.GP_Municipality,
                    Block = edit.Block,
                    BranchID = edit.BranchID,
                    BranchAddress = edit.BranchAddress,
                    BranchCode = edit.BranchCode,
                    BranchName = edit.BranchName,
                    BranchTypeID = edit.BranchTypeID,
                    DistrictID = edit.DistrictID,
                    IsActive = edit.IsActive,
                    PostOffice = edit.PostOffice,
                    StateID = edit.StateID,
                    Vill = edit.Vill,
                };
                model.Owners = new List<BranchCreateOwnerRequestModel>();
                int tempId = 0;
                foreach (var item in branch.BranchOwners)
                {
                    model.Owners.Add(new BranchCreateOwnerRequestModel()
                    {
                        TempOwnerID = tempId,
                        AadharNo = item.AadharNo,
                        BranchID = item.BranchID,
                        BranchOwnerID = item.BranchOwnerID,
                        Designation = item.Designation,
                        DOB = item.DOB,
                        DOJ = item.DOJ,
                        EmailAddress = item.EmailAddress,
                        IsActive = item.IsActive,
                        OwnerName = item.OwnerName,
                        PanNo = item.PanNo,
                        PrimaryContactNo = item.PrimaryContactNo,
                        QualificationID = item.QualificationID,
                        SecondaryContactNo = item.SecondaryContactNo,
                        VoterNo = item.VoterNo


                    });
                    tempId++;
                }
            }







            var branchType = _service.Get<object>(_global.ApiUrl() + "/api/v1/branch/getbranchType");
            var State = _service.Get<object>(_global.ApiUrl() + "/api/v1/branch/getAllState");
            var District = _service.Get<object>(_global.ApiUrl() + "/api/v1/branch/getAllDistrict");

            var branchTypeList = JsonConvert.DeserializeObject<ApiResponseViewModel<BranchTypeDataModel>>(JsonConvert.SerializeObject(branchType.Item3)).Data;
            var Statelist = JsonConvert.DeserializeObject<ApiResponseViewModel<StateDataModel>>(JsonConvert.SerializeObject(State.Item3)).Data;
            var distructList = JsonConvert.DeserializeObject<ApiResponseViewModel<DistrictDataModel>>(JsonConvert.SerializeObject(District.Item3)).Data;

            model.BranchTypeList = branchTypeList;
            model.StateList = Statelist;
            model.DistrictList = distructList;




            TempData["BranchMaster"] = model;
            ViewBag.LastId = BranchID.HasValue ? model.Owners.Count() : 0;
            return View(model);
        }
        [HttpPost]

        public ActionResult AddUpdateBranch(BranchDetailsInsertUpdateRequestModel model)
        {
            if (!ModelState.IsValid)
                return View(model);
            var branch = new BranchDetailsInsertUpdateRequestModel();
            model.BranchCode = "";
            //  model.GP_Municipality = "GPM";
            if (TempData.ContainsKey("BranchMaster"))
            {
                branch = TempData["BranchMaster"] as BranchDetailsInsertUpdateRequestModel;
            }
            TempData.Keep();
            model.DistrictList = branch.DistrictList;
            model.BranchTypeList = branch.BranchTypeList;
            model.StateList = branch.StateList;
            model.Owners = branch.Owners;




            var jSon = new JavaScriptSerializer().Serialize(model);
            var res = _service.Post<CommonResponseDataModel>(_global.ApiUrl() + "/api/v1/branch/insertupdatebranch", jSon);
            //if (TempData.ContainsKey("BranchMaster"))
            //{
            //    branch = TempData["BranchMaster"] as BranchDetailsInsertUpdateRequestModel;
            //}
            //TempData.Keep();
            //model.DistrictList = branch.DistrictList;
            //model.BranchTypeList = branch.BranchTypeList;
            //model.StateList = branch.StateList;
            //model.Owners = branch.Owners;
            if (res.Item3 != null && res.Item3.ReturnID > 0)
            {
                model.BranchID = res.Item3.ReturnID;
                model.BranchCode = res.Item3.ExtraFiled ?? string.Empty;
                ViewBag.LastId = model.Owners.Count();

                return View(model);
            }
            ViewBag.Error = "Unable to add new branch!";
            ViewBag.LastId = model.Owners.Count();

            return View(model);
        }

        public ActionResult AddNewOwner(int LastId)
        {
            ViewBag.LastId = LastId;

            return PartialView("_InsertUpdateBranchOwner", new BranchCreateOwnerRequestModel() { OwnerIndexNo = LastId });

        }
        [HttpPost]
        public ActionResult InsertUpdateBranchOwner(List<BranchCreateOwnerRequestModel> model)
        {
            var jSon = new JavaScriptSerializer().Serialize(model);
            var res = _service.Post<CommonResponseDataModel>(_global.ApiUrl() + "/api/v1/branch/insertupdatebranchowner", jSon);
            if (res.Item3 != null && res.Item3.ReturnID > 0)
                return Json(new { IsSucess = true }, JsonRequestBehavior.AllowGet);

            return Json(new { IsSucess = false }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult BranchUsers()
        {
            var _BranchDetails = _service.Get<ApiResponseViewModel<BranchUserMappingDeatils>>(_global.ApiUrl() + "/api/v1/branch/getbranchusers").Item3;
            BranchUserMappingDeatils data = _BranchDetails.Data.FirstOrDefault();

            return View(data);
        }

        public ActionResult BranchQuery()
        {
            var _branchQuery = _service.Get<ApiResponseViewModel<BranchQueryViewModel>>(_global.ApiUrl() + "/api/v1/branch/getbranchQueryDetails").Item3;

            return View(_branchQuery?.Data ?? new List<BranchQueryViewModel>());
        }

        [HttpGet]
        public ActionResult UpdateIsReadBranchQuery(int branchQueryID, bool isRead)
        {
            var res = _service.Get<CommonResponseDataModel>(_global.ApiUrl() + "/api/v1/branch/updateIsReadBranchQuery?BranchQueryID=" + branchQueryID + "&IsRead=" + isRead).Item3;
            if (res != null && res.ReturnID > 0)
                return Json(new { IsSucess = true }, JsonRequestBehavior.AllowGet);
            return Json(new { IsSucess = false }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult StudentQuery()
        {
           var jSon = new JavaScriptSerializer().Serialize(new StudentQueryRequestDataModel());
            var _studentQuery = _service.Get<ApiResponseViewModel<StudentQueryViewModel>>(_global.ApiUrl() + "/api/v1/student/Query/All").Item3;

            return View(_studentQuery?.Data ?? new List<StudentQueryViewModel>());
           // return View();
        }

        [HttpGet]
        public ActionResult UpdateIsReadStudentQuery(int studentQueryID, bool isRead)
        {
            var res = _service.Get<CommonResponseDataModel>(_global.ApiUrl() + "/api/v1/student/Query/IsRead?StudentQueryID=" + studentQueryID + "&IsRead=" + isRead).Item3;

WEB/Controllers/ClassController.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using Web.Core.Common;
using Web.Core.Interface;
using Web.Core.ViewModel;

namespace WEB.Controllers
{
    public class ClassController : Controller
    {
        IGlobal _global;
        CommonServices _service;

        public ClassController(IGlobal global)
        {
            _global = global;
            _service = new CommonServices(_global);

        }

        // GET: Class
        public ActionResult Index()
        {
            var _ClassDetails = _service.Get<ApiResponseViewModel<ClassMasterDataModel>>(_global.ApiUrl() + "/api/v1/class/getclassdetails").Item3;
            return View(_ClassDetails.Data);
        }

        //Get Class By Name
        [HttpPost]
        public ActionResult Index(String ClassName)
        {
            var param = string.IsNullOrEmpty(ClassName) ? "" : "?className=" + ClassName;
            var _ClassDetails = _service.Get<ApiResponseViewModel<ClassMasterDataModel>>(_global.ApiUrl() + "/api/v1/class/getclassdetails" + param).Item3;
            return View(_ClassDetails.Data);
        }

        public ActionResult AddUpdateClass(int? ClassID = null)
        {
            ClassInsertUpdateRequestModel model = new ClassInsertUpdateRequestModel();

            var _SessionList = _service.Get<ApiResponseViewModel<SessionMasterDataModel>>(_global.ApiUrl() + "/api/v1/session/getsessiondetails").Item3;
            var ddlSessions = JsonConvert.DeserializeObject<ApiResponseViewModel<SessionMasterDataModel>>(JsonConvert.SerializeObject(_SessionList)).Data;
            model.ddlSessions = ddlSessions;

            if (ClassID.HasValue)
            {
                var _ClassDetails = _service.Get<object>(_global.ApiUrl() + "/api/v1/class/getclassdetails?ClassID=" + ClassID);
                var outout = JsonConvert.DeserializeObject<ApiResponseViewModel<ClassMasterDataModel>>(JsonConvert.SerializeObject(_ClassDetails.Item3))?.Data?.FirstOrDefault();
                if (outout != null)
                {
                    model.ClassID = outout.ClassID;
                    model.ClassName = outout.ClassName;
                    model.ClassDescription = outout.ClassDescription;
                    model.IsActive = outout.IsActive ? 1 : 0;
                    model.SessionID = outout.SessionID;
                }
            }

            return View(model);
        }

        [HttpPost]
        public ActionResult AddUpdateClass(ClassInsertUpdateRequestModel model)
        {
            if (!ModelState.IsValid)
                return View(model);

            var identity = User.Identity as ClaimsIdentity;
            var userID = identity.Claims.Where(m => m.Type == "UserID").FirstOrDefault().Value ?? "0";
            model.CreatedBy = Convert.ToInt32(userID);

            var jSon = new JavaScriptSerializer().Serialize(model);
            var res = _service.Post<CommonResponseDataModel>(_global.ApiUrl() + "/api/v1/class/insertupdateclass", jSon);

            if (res.Item3 != null && !res.Item3.Successful)
            {
                ViewBag.Error = "Unable to save class!";
            }

            if (res.Item3 != null && res.Item3.ReturnID > 0)
            {
                model.ClassID = res.Item3.ReturnID;

                return RedirectToAction("Index");
            }

            return View(model);
        }

    }
}

WEB/Controllers/SectionController.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using Web.Core.Common;
using Web.Core.Interface;
using Web.Core.ViewModel;

namespace WEB.Controllers
{
    public class SectionController : Controller
    {
        IGlobal _global;
        CommonServices _service;

        public SectionController(IGlobal global)
        {
            _global = global;
            _service = new CommonServices(_global);

        }

        // GET: Section
        public ActionResult Index()
        {
            var _SectionDetails = _service.Get<ApiResponseViewModel<SectionDataModel>>(_global.ApiUrl() + "/api/v1/section/getsectiondetails").Item3;
            return View(_SectionDetails.Data);
        }

        //Get Section By Name
        [HttpPost]
        public ActionResult Index(String SectionName)
        {
            var param = string.IsNullOrEmpty(SectionName) ? "" : "?SectionName=" + SectionName;
            var _SessionDetails = _service.Get<ApiResponseViewModel<SectionDataModel>>(_global.ApiUrl() + "/api/v1/section/getsectiondetails" + param).Item3;
            return View(_SessionDetails.Data);
        }

        [HttpGet]
        public ActionResult AddUpdateSection(int? SectionID = null)
        {
            SectionInsertUpdateRequestModel model = new SectionInsertUpdateRequestModel();

            var _ClassList = _service.Get<ApiResponseViewModel<ClassMasterDataModel>>(_global.ApiUrl() + "/api/v1/class/getclassdetails").Item3;
            var ddlClass = JsonConvert.DeserializeObject<ApiResponseViewModel<ClassMasterDataModel>>(JsonConvert.SerializeObject(_ClassList)).Data;
            model.ddlClass = ddlClass;

            if (SectionID.HasValue)
            {
                var _SectionDetails = _service.Get<object>(_global.ApiUrl() + "/api/v1/section/getsectiondetails?sectionID=" + SectionID);
                var outout = JsonConvert.DeserializeObject<ApiResponseViewModel<SectionDataModel>>(JsonConvert.SerializeObject(_SectionDetails.Item3))?.Data?.FirstOrDefault();
                if (outout != null)
                {
                    model.SectionID = outout.SectionID;
                    model.SectionName = outout.SectionName;
                    model.SectionDesc = outout.SectionDescription;
                    model.IsActive = outout.IsActive ? 1 : 0;
                    model.ClassID = outout.ClassID;
                }
            }

            return View(model);
        }

        [HttpPost]
        public ActionResult AddUpdateSection(SectionInsertUpdateRequestModel model)
        {
            if (!ModelState.IsValid)
                return View(model);

            var identity = User.Identity as ClaimsIdentity;
            var userID = identity.Claims.Where(m => m.Type == "UserID").FirstOrDefault().Value ?? "0";
            model.CreatedBy = Convert.ToInt32(userID);

            var jSon = new JavaScriptSerializer().Serialize(model);
            var res = _service.Post<CommonResponseDataModel>(_global.ApiUrl() + "/api/v1/section/insertupdatesection", jSon);

            if (res.Item3 != null && !res.Item3.Successful)
            {
                ViewBag.Error = "Unable to save section!";
            }

            if (res.Item3 != null && res.Item3.ReturnID > 0)
            {
                model.SectionID = res.Item3.ReturnID;

                return RedirectToAction("Index");
            }

            return View(model);
        }
    }
}

WEB/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Scholl Admin</title>

    <!-- Custom fonts for this template-->
    <link href="~/Content/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    @*  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">*@

    <!-- Custom styles for this template-->
    @*<link href="css/sb-admin-2.css" rel="stylesheet">*@
    @Styles.Render("~/bundel/RenderCss")
</head>

<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        @Html.Partial("_PartialMenu")
        <!-- End of Sidebar -->
        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">
                @Html.Partial("_PartialHeader")

                <!-- Begin Page Content -->
                @RenderBody()
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->

            @Html.Partial("_PartialFooter")
            <!-- Footer -->
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <a class="btn btn-primary" href="/login/logoff?isLogout=true">Logout</a>
                </div>
            </div>
        </div>
    </div>

    <!-- Bootstrap core JavaScript-->
    <!--<script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>-->
    <!-- Core plugin JavaScript-->
    <!--<script src="vendor/jquery-easing/jquery.easing.min.js"></script>-->
    <!-- Custom scripts for all pages-->
    <!--<script src="js/sb-admin-2.min.js"></script>-->
    <!-- Page level plugins -->
    <!--<script src="vendor/chart.js/Chart.min.js"></script>-->
    <!-- Page level custom scripts -->
    <!--<script src="js/demo/chart-area-demo.js"></script>
    <script src="js/demo/chart-pie-demo.js"></script>-->
    @Scripts.Render("~/bundles/RenderJs")
    @RenderSection("script", false)
</body>

</html>

WEB/Views/Shared/_Layout_bk.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

WEB/Views/Shared/_PartialFooter.cshtml
<footer class="sticky-footer bg-white">
    <div class="container my-auto">
        <div class="copyright text-center my-auto">
            <span>Copyright &copy; Your Website 2020</span>
        </div>
    </div>
</footer>

WEB/Views/Shared/_PartialMenu.cshtml
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

    <!-- Sidebar - Brand -->
    <a class="sidebar-brand d-flex align-items-center justify-content-center" href="index.html">
        @*<div class="sidebar-brand-icon rotate-n-15">
                <i class="fas fa-laugh-wink"></i>
            </div>*@
        <div class="sidebar-brand-text mx-3">Brand Name</div>
    </a>

    <!-- Divider -->
    <hr class="sidebar-divider my-0">

    <!-- Nav Item - Dashboard -->
    <li class="nav-item active">
        <a class="nav-link" href="index.html">
            <i class="fas fa-fw fa-tachometer-alt"></i>
            <span>Dashboard</span>
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
            <i class="fas fa-fw fa-user"></i>
            <span>Users</span>
        </a>
        <div id="collapseOne" class="collapse" aria-labelledby="headingOne" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                @Html.ActionLink("Users", "Index", "Users", null, new { @class = "collapse-item" })

                @* @Html.ActionLink("Add/Update Branch", "Branch", "AddUpdateBranch", new { @class = "collapse-item" })*@
                @* <a class="collapse-item" href="#" @Html.ActionLink("Home", "Index", "Home")>Add/Update Branch</a>*@
            </div>
        </div>
    </li>

    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">
            <i class="fas fa-fw fa-cog"></i>
            <span>Branch</span>
        </a>
        <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                @Html.ActionLink("Branch", "Index", "Branch", null, new { @class = "collapse-item" })

                @Html.ActionLink("Add/Update Branch", "AddUpdateBranch", "Branch", null, new { @class = "collapse-item" })
                @Html.ActionLink("Branch Query", "BranchQuery", "Branch", null, new { @class = "collapse-item" })
                @Html.ActionLink("Student Query", "StudentQuery", "Branch", null, new { @class = "collapse-item" })
                @* <a class="collapse-item" href="#" @Html.ActionLink("Home", "Index", "Home")>Add/Update Branch</a>*@
            </div>
        </div>
    </li>

    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseThree" aria-expanded="true" aria-controls="collapseThree">
            <i class="fas fa-fw fa-cog"></i>
            <span>Student</span>
        </a>
        <div id="collapseThree" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                @Html.ActionLink("Session Master", "Index", "Session", null, new { @class = "collapse-item" })
                @Html.ActionLink("Class Master", "Index", "Class", null, new { @class = "collapse-item" })
                @Html.ActionLink("Section Master", "Index", "Section", null, new { @class = "collapse-item" })
            </div>
        </div>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider d-none d-md-block">

    <!-- Sidebar Toggler (Sidebar) -->
    <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
    </div>

</ul>